### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by hosamshahin** [abelosorio/sequelize-views-support#1]
import Sequelize from 'sequelize-views-support';
^^^^^^

SyntaxError: Unexpected token import

$ node -v
v8.2.0

**Comment by abelosorio** [comment]
Hi @hosamshahin, try with:

```javascript
const Sequelize = require('sequelize-views-support');
```

I'll update the documentation.
Let me know if that works please.

Thanks!

**Comment by hosamshahin** [comment]
Thanks, I changed the import line to 

var Sequelize = require('sequelize-views-support');

now I'm getting the following error:

var sequelize = new Sequelize(
                ^
TypeError: Sequelize is not a constructor

**Comment by abelosorio** [comment]
mmm right.

Try with `var Sequelize = require('sequelize-views-support').default`.

In the meantime I'll do some adjustments there so you can use it without `default`.

**Comment by abelosorio** [comment]
OK @hosamshahin I made those changes in version 1.1.0. Be sure to install it: `npm install --save sequelize-views-support@next`.

```javascript
const Sequelize = require('sequelize-views-support');

const sequelize = new Sequelize(/* ... */);
```

Let me know if that works as expected.

Thanks

**Comment by hosamshahin** [comment]
Thank you, Now I got a new error:

`~/app/node_modules/sequelize-views-support/build/index.js:37
    return _possibleConstructorReturn(this, (SequelizeViewsSupport.__proto__ || Object.getPrototypeOf(SequelizeViewsSupport)).apply(this, arguments));
                                                                                                                              ^

TypeError: Class constructor Sequelize cannot be invoked without 'new'`

**Comment by abelosorio** [comment]
Hi @hosamshahin, sorry for beign unresponsive, yesterday was a very busy day for me.

Please try the 1.2.0 version, it has the fix for your problem, and this time *I tested it*.

Sorry for any inconvenience, and thanks for your contribution.

**Comment by hosamshahin** [comment]
Thanks @abelosorio, that actually worked!

**Comment by abelosorio** [comment]
Great! Thanks for your contribution!
