### ISSUE TITLE
DROP VIEW failing

### ISSUE THREAD

**Issue by idahogurl** [abelosorio/sequelize-views-support#2]
Inside query-interface-views-support.js, on line 4, you have 

const sql = `
      DROP VIEW IF EXISTS "${viewName}"${options.cascade && ' CASCADE'}
    `;

That creates "DROP VIEW IF EXISTS someViewundefined"

It should be 
const sql = `
      DROP VIEW IF EXISTS "${viewName}" ${options.cascade ? 'CASCADE': ''}
    `;

**Comment by abelosorio** [comment]
Thanks @idahogurl. I'll fix it right now.

**Comment by abelosorio** [comment]
@idahogurl fix is in version 1.2.1.

Thanks!
