### ISSUE TITLE
pg@6.1.2 support

### ISSUE THREAD

**Issue by idahogurl** [abelosorio/sequelize-views-support#3]
Is there any reason why you are using the pg@7 package. That package has known issues with Sequelize. Would you be willing to set your package.json file to ^6.1.2

**Comment by abelosorio** [comment]
Hi Rebecca, I didn't know that. Do you have any reference to read about it?

I'll Google it so I can be objective in my answer to this :)

Thanks for reporting it.

Bests

**Comment by abelosorio** [comment]
Hi @idahogurl, sorry for delay.

I've been searching issues related to pg@7 and Sequelize and I can't understand if they already fixed it or not... They say so but users say the opposite.

- https://github.com/sequelize/sequelize/issues/7998
- https://github.com/brianc/node-postgres/issues/1372
- https://github.com/sequelize/sequelize/issues/7818

Anyway... I decided to downgrade to pg@6.x as you proposed.

Thanks

**Comment by abelosorio** [comment]
Published at version 1.2.2 :point_right: https://www.npmjs.com/package/sequelize-views-support

**Comment by parthakuila** [comment]
yes only work in _ npm install pg@6.1.2
