### ISSUE TITLE
"Table 'myView' already exists" on soft sync

### ISSUE THREAD

**Issue by GheorgheP** [abelosorio/sequelize-views-support#4]
The situation is that i have a already defined schema so I cannot do force sync. On normal table the soft sync does work. You even can add a view on a already existent schema. But when trying to do a soft sync when you have already, the error is thrown: ` Table 'myView' already exists`.

**Comment by abelosorio** [comment]
Hi @GheorgheP! First of all, thanks for your contribution.

The `sync` method should be used to synchronize the schema when it does not exist yet. The best practice to manipulate the current schema is by the use of migrations.

Hence, the steps to add a new view are:

- Write the view model.
- Write a migration to add this view to the schema.

Let me know if it helps.

Regards, Abel.

**Comment by GheorgheP** [comment]
@abelosorio, thanks for fast response. I fixed my issue already using `syncView`: https://github.com/abelosorio/sequelize-views-support/issues/5

I know this is not part of this issue, but could you recommend a good migration tool for sequelize? As honestly I do not have migrations now, but I will need them.

Thanks.
